[burrow]
version = "0.1.0"

[recipients]
test = "age1s67d97stmwe9acq5kxfwmmu2u46zygy5nq5rtlaxgwupen0vcyns23tjll"

[secrets]
KEY1 = """
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJb05mcVFXVW9WMTlnQURX
d29ycTBBSHlESCtSaEFmVEtISE5mb3llbm13CjVpcHJuUE1BS3NHRC80QmxCVndv
am5sNnRBM3VMZi9ZOGtvL2lYMkRsMXcKLT4gKkJwc3wtZ3JlYXNlCklOUkVKejZj
ZTNFb3VmdXlhYk16bG5JZEU0SEtqY2pmWFhScUhGUW12aGszRUlrZDZjV3B6U0lJ
NjErWTNJN2cKemR3Sy9OL3BWRnpxeFlGSkdpdW5vdVEKLS0tIDJZMjdUZXphWFZm
cEVPT2FwNmdCc28wNHZiUEREVGtYaTNEanMrYml5cXMKrwC3fWRRY2IedtSuSxmH
8B0u1KCnARS9eNlB5DhajYaHOUFzkuQF3rKskkwFrIILKA==
-----END AGE ENCRYPTED FILE-----
"""
KEY2 = """
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMXZjbElWeSs0d1VrZzF5
Tm1xV0VFSmEzbFV6aEZwNTlwc3o0ZmhLeUJvCkFWTDFzWG53TjhBeW5Gd1hUYUFI
a3JLdmJxTjBiQUlOVVowU1Bsd3NreWsKLT4gO3dqaT5gLWdyZWFzZSAvV0VdCmw1
aU50aHU1dE0zdC9jTXdUUHMvTkl3Z0JnRmxOSTc0SXQ4dXdZZy9YY29TOVpTSHRp
bTZ6Vit1b1J5bytpUTkKMTBzOWtXTWFicG1vVmZ1OHFSSFdCaENHSFVHSAotLS0g
OEg2YXRlL2VZMms0RjN4a3RQenZ6YWs5dzB4Z01EbEpBZkdFL3lTWDJpUQrD8UfM
14Btq21jmZTvpFg1UAuEM33EgMpT7PGY9+Drg3ONfWgD7k+2ujx8XAo=
-----END AGE ENCRYPTED FILE-----
"""
KEY3 = """
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMGoxTGllcm9ubUFMOG5O
ZnpsTXg5bUttbjNSa3Z4TnZaV2hIYVFsMFRnCjhiZzBlVFRDTUp1UmhjNFBVSG55
NHlHbTFyUG56Ym8rOWlidU82emhWblEKLT4gYS1ncmVhc2UKQ2dFRGhUTVJ2djNh
WDFpSWJmTEd6dUh2VVJhNQotLS0gUlpXSzNxYjU1ODRGcEpHUkJNd0d3QlpNSkJq
a0prYWVUY0Y3VjdSM3hvRQq9R7u1H6Bf0IBqE9gujFGbtb1JMIR5CLlZ/thysd1+
3pb+7KfOnVsyPg==
-----END AGE ENCRYPTED FILE-----
"""
