[burrow]
version = "0.1.0"

[recipients]
alice = "age1h80ycd95w09ks74qsncun2muh7xlgupqvqtwyfawwrsk2q44gunqhlhm8x"

[secrets]
KEY_ONE = """
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cDgrOWNTcXM3RE5MWlJ5
WjEvMnFQVDhIV1I1ZDBwNEFUdk5YRTc3UFY4CjdRajU2MTN0RmpDa01mdWExYmxN
dFVJNzRkY1dnNXVwOGlETWY5VmZXT0UKLT4gWmxMcWR6dy1ncmVhc2UgfjFRPiBP
CjNiU3BUVVpZZUFBM0NqbEFrVVQ4Q1JRY0ZJZ1FkelBJS0E4MXdvV0pUNEtObnZ5
L3FMUVltTiswWHkvd3psbkkKR2xBV1hEL1U3QlkKLS0tIE1mU3QvVXQ4bFlIMnc3
R0w4cWFHbHNxTXIwV0NiWkU4NGI1cW5aSFZBR3cK9q8QXwJP7b7UBcOnH8qQ1GM3
vp3ZQzqfZo8ipW5Z/wVQEswk8S0=
-----END AGE ENCRYPTED FILE-----
"""
KEY_THREE = """
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOUtZbHdZWFJUd0JiTCtQ
NGhqRnMwV1d3QXpvNFlvcEFwTXE1TnZhMWtRCjkwSHZub2xkajUxOVR6RWJ6S1dk
clE0WGlUSmttV2Zwc05xWXp0QnB4UDAKLT4gYzApT2MlLWdyZWFzZSBhCkg4WjdR
TzF6eFJrdjJjRlRaV3MxWTN6WAotLS0gQy9GM1FGeVQwdlhDMVFTalRSMU5EalR1
RWQxRFRtVWhJUUZSK1NVcWNxSQrngmnQbVwH5CMgB+MSfodfcxeVopouIP55yRB9
8dxU5GTALNhNKg==
-----END AGE ENCRYPTED FILE-----
"""
KEY_TWO = """
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOY3VETC90Smp3ZmtvUXl1
QmtQc2NxdVUzVGJIMVI1SGZvL0IxUThjdzNRCmNVaFhhN2hYMEIxVEgzVUQvam5w
eVgwNGFhR2lxa2ZWemhYUGkwS2tMTVkKLT4gSVwueGAtZ3JlYXNlIEV9X2IgIVkg
XmcKT2hZcElWU3JzMXNyR2dIRTIzYUN6V1dEK0x1c0FpZ0V3dno3UEs4VUlaZm92
ZTRBMTVCclo0UXQxYzRhb1o1NQpDNWUxZEZIOURnR2YwTlJ0aUYrZU0xbVdXeHlC
MFEKLS0tIHBpejkwSnJ3eUNzM0Rhd0ZNa1Y1Mmt6RkhBUmN1WmlUV1Y0WlNaTXZr
THMKETQYr8XvIAJ1Z3TxKcBQF9Qv3EJ8xt2wPZXRFfmkgSyNe/qT8Zs=
-----END AGE ENCRYPTED FILE-----
"""
