[burrow]
version = "0.1.0"

[recipients]
test = "age19pess60suymvc96zwe3mktwskkvsqn9aux7g60kw2dcyt6dtys7q27srpv"

[secrets]
KEY1 = """
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScW5rc3B2QytWcjEvWXJo
bTJ4ZWw3S0xsS1VrZTVyNU1hY2F3aVpOMXdjCmFCbHZueVV2a253WWJ4THlQNHhs
SVA5ZDIvYmNzL1d5UzFaRW1HbExtMjgKLT4gLC1ncmVhc2UKSU5wYWlHL3ErSzkx
TEo1eDBTdU9FMFVUY0FmN3ZIYno5eFJ2RkdqT01FSmNudlRTSDZoQTlkdi9pVmtY
dnRGTwo1YzNNRGJXTElQZ0haQlpxRHM0d1E4MmJhU08rCi0tLSAvcDZUSTRTTith
bzZ3a0MySC9aclFoODczSEZDNlpZeXhhSEpRVWhBalVJCpSWOqMY3tLix0fmDP/n
mqsYDx0CUnt0fm88VNPd82Fu2oc+vbZU7B9k56SOJIjmkoU=
-----END AGE ENCRYPTED FILE-----
"""
KEY2 = """
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYkZyNVZOeTg0bGxraG1x
NVZWU0VlVFF2MzdDUUgwcWdRVkNsMVlLYlRVCk9heGpMYmtoQzdNak9ha0tBRVZ5
d0VxQXFBdXF3UFozdFQ1NWdqUEFoR2cKLT4gMCRZXTwtSkwtZ3JlYXNlICUgRXki
YEMgUmQgezgKRXFVQkszeHFUd1JyeGUyS0NTdUlUbG42eHlUb3VJSFE5OUlyS0V6
M2lEV2RPMWlyc3VVdHh1Zk91NHRWakJBdwpraStCdGR5a2RZSENlcElubUluagot
LS0gOWs2N0krZEFjS2U0TnY1Y2Y5UTQ3VHp6TVJIeXNPZDBDNVVLZjdrZTRNOApO
aKAaygo4o61gED0uIxK+TBdXHsmpwQBFk320OBPPB1XeB5rYF6GyDXw/FmE=
-----END AGE ENCRYPTED FILE-----
"""
KEY3 = """
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOKzA3dWhZbHkxVkcrVTRG
UnN2Wk5BZmxnSlllck9jQ2UzVkk1WUZ0UkNVCndjZDNIYzFtOXJ2UkJFdFNMRkND
QWxhUDg3K3VwWGg1bi92TEwyOFJLNlkKLT4gJzdSSmUuLWdyZWFzZSA0Ygo5VGFk
MnhaNGF0dHJ2QUxSTnBIMnB6UENVZlZCRnNlMzUzUEVGZ3U0VzJySm1OcFQrenRi
dFVQcWxmbTlMRHRlCmgyVzNLRlI5ZlBOYzVZZ3lXSno4QzBYdytOaTNYeFdqRlZ1
MWFxTnFuOTJWNERnMHZnLzZFSHZ1c0EKLS0tIDJkVE10cWhreEYwN0prYnpPRjNY
c1pteS8wM0xDZWEzMkY3U3NaZTUwMVEKYqrDCNrA+ql3jnHlzmCbrha5KNKxi0qI
4b0hpyiKJ1QsUkCCmgyTX0c=
-----END AGE ENCRYPTED FILE-----
"""
