[burrow]
version = "0.1.0"

[recipients]
alice = "age145xgmj2nutnuaftfdfdhqk0l89yt58se22au2dznrfxkkq6ueetsnexgxt"
bob = "age1gut5vmctm9d5jfevhzrmq8xartdzrqtquh0pfg56gsatfp6uvehqamcmg5"

[secrets]
TEAM_SECRET = """
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieEg3MGZXUFl4cW5VNmpO
aERRZnFKTXZwK3FNeXBrMmVZRE93RUVBekV3ClhpV2tGUmtsV0pid1VOWjZOdzJn
ai9QK0xMS1BPcVROdUZMbmkrNFB5MDgKLT4gWDI1NTE5IGFFc3J2MkxJUzFsejVO
eW9zd0VnbmkxQ0VXMVFmeEpRb0F2VWlBcmNuMWsKNnBUTlZSU0E3Z096aDRMOHdT
WEs0WkVVNFJOaTEyM3pkR215ajIxa05yVQotPiBOeGs3XHg6MC1ncmVhc2UKRGZ2
RDRBc1VpS0g3TzVsS05jV0x6aU1GYmxtNnp0RURlMlUxVS9iMHN1N0dMUFE2eEoz
SnJMQUMrdnFHTzc0dgp1Nit2d1B4dkU3ZEdpVmIxNXRKS0kyYTRzWjhGZWxBZjlk
aHdlQ053clNQcnNLV21sbGdKCi0tLSBFN2tUNWxtS0F4R3pVY1RaeGxXTVo5ZlBu
cDBsY1U4aE5CWjFTSWY3S21rCtJI9fw96yKAk7h/9VNQKfnVinkne9CAWv9aWbJ0
TKNGyisnpOb7ixo=
-----END AGE ENCRYPTED FILE-----
"""
