[dugout]
version = "0.1.2"

[recipients]
alice = "age1wru8zgryw3z75aw2ryfgv7jzn7dsqqw297cn8kgna7gf6c4wdezql23uqj"

[secrets]
KEY_ONE = """
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VHN3dnpET1Rwb1R2SW1E
akZpV1BiaGgrZi9ic3daQnJucDZhcUxJU0FzCkhOOFRuZVlJWi9TOFRHbHVZOWxC
dDJwaGhlNFRaRGFhM3dLdkdxeDJxdW8KLT4gWGNzYi1ncmVhc2UgOn1KPTYKZEhQ
eXl3elgxVFFWSkUweGVBNmw4L3doWTVPYjM2QzJ3RjBvTS9zdzUyRWtxeVhxOTR2
TWhTVEkwQnJFWE5XbwpiTkVJMm03QWllazNpZwotLS0gaTNBKzVZbEVHV3N2cHRU
Nzkva3pCWmJXb3poODQvMFh1WlpQRUx6K2hmYwr5Za2r8fOg/P97Hbx1YYNUN24D
OW5QitSrmIocf9PXr9Gv+rgPfw==
-----END AGE ENCRYPTED FILE-----
"""
KEY_THREE = """
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwalpmUkNNc2V1Z0JtcjlL
V0hmT25EL0ZyaXFFa29odVhXVFhvS0c5OFZJClFxOFh4VHVzVXJQd28yeWFSWFVK
NHNKTkhoYnNIU2VIN1QrZWwrR3lxYjgKLT4gOHAkMnI+by1ncmVhc2UgLCArNH5+
ICV3CjN0WlRDTDBzeUx4T0x1V1RURTBwRjIrTlI0Qi8rSElOcWJ6a0VxSVEwNjk0
QlRkM1F5TldXQzI3bERYTmJBZ0MKMTlQNDBZaTRYMkIrZXRBOHhISTZCVUY3d2xy
UVJEOUpURjQKLS0tIHRaR3BxeWg0SGF5NmRRMzE5UUZ1Z3YxSmNDeG1qdHFlSHIv
Zi81THBMV1EKzf62YJp6MlMPTGMT4tgYmbxcdeHmrC146JXPE4gpMd97+HYp5uU=
-----END AGE ENCRYPTED FILE-----
"""
KEY_TWO = """
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VnhXQUkramczRWF3bFRU
LzMybE55UHFQUWRhZlJia2x6UC9TK3FVcVdBCktiQ3RRVUV5cExZdWUxUDNGQ2k0
Wm9KV3N6K3l5SnJwM25QVS9iOVlrYncKLT4gLGJVTDA7LWdyZWFzZSBtPXwubjQg
KVxXeXs2ID4KZzVraThsVEVXMmtQOHdPOEF1cTBPVFQxbGhubTlrSUZnY3hxQS9n
dnh6aTdJN2krSGZQR1ZxS0pCczNkCi0tLSBrNFdmRUtCUzl4MGlkVUE0Nk9JWXJZ
UDZoVFNWVmoyaUVRQ0xWbWtPVlRrCrAw1ECyDnOG9hLUSRI77wXCsUDGkPGoZonA
I72NqLAJumWhrGN4
-----END AGE ENCRYPTED FILE-----
"""
